# Exception

## In 서블릿

### 서블릿 예외처리

서블릿은 두가지 방식으로 예외 처리를 지원한다
1. `Exception`
   - 자바 직접 실행
     - 자바의 메인 메서드를 직접 실행하는 경우, `main` 쓰레드가 실행
     - 예외가 발생한 경우 콜 스택을 따라 자신을 호출한 상위 메서드로 계속 올라가게 되고 결국 `main()`을 만나 예외 정보를 넘기고 종료된다
   - 웹 어플리케이션
     - 사용자 요청별로 쓰레드가 할당, 서블릿 컨테이너 안에서 실행
     - 예외가 발생한 경우 try-catch로 예외를 처리하면 문제가 없지만, 만약 이를 처리하지 않은 경우 어떻게 될까?
     - 즉 예외가 상위 메서드로 계속 전달되며 서블릿 밖가지 전달되면?
       - `컨트롤러(Excpetion) -> 인터셉터 -> 서블릿 -> 필터 -> WAS(여기까지 전파)`
     - WAS까지 예외가 전달되는데, 여기까지 올라오게 되면 어떻게 처리해야될까?
       - 이렇게 WAS까지 예외가 전달되면, 서버 내부에서 처리할 수 없는 오류로 생각해 `Internal Server Error(500)`를 반환한다
       - 반면 페이지가 없는 리소스를 호출하면 `Not Found(404)`에러를 반환한다
2. `response.sendError`: 파라미터 (HTTP 상태코드, 오류메시지)
   - `HttpServletResponse`가 제공하는 `sendError` 메서드 또한 사용가능하다
   - 이 메서드를 사용하면 HTTP 상태코드와 오류메시지를 추가할 수 있다.
     - `컨트롤러(response.sendError) -> 인터셉터 -> 서블릿 -> 필터 -> WAS(sendError 호출 기록 확인)`
     - 서블릿 컨테이너는 사용자에게 보여주기 전에 `sendError()`가 호출되었는지 확인하고, 오류코드에 맞추어 오류페이지를 보여준다.

즉, `Exception`이 발생하면 무조건 500 에러, 내가 직접 `sendError`를 통해 처리를 했으면 오류코드에 맞춰 페이지가 등장한다.